# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI
#on: [workflow_dispatch]

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{matrix.os}}

    strategy:
      max-parallel: 24
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run prettier
    - run: npm run linter
    - run: npm test


    #- name: Publish Unit Test Results
    #  uses: EnricoMi/publish-unit-test-result-action@v1
    #  if: always()
    #  with:
    #    files: test-results/*.xml

  upload-data-job:
    name: Upload data to artifact
    runs-on: ubuntu-latest
    steps:
      - name: Upload hello world file
        uses: actions/upload-artifact@v1
        with:
          name: logs
          path: test-results/test.html

  download-data-job:
    name: Download data from artifact
    needs: upload-data-job
    runs-on: ubuntu-latest
    steps:
      - name: Upload hello world to artifact
        uses: actions/upload-artifact@v1
        with:
          name: logs
          path: test-results/test.html
